- name: Install required applications and dependencies
  hosts: jenkinsfleet
  tasks:
   - name: Ping my hosts
     ansible.builtin.ping:
   - name: Print message
     ansible.builtin.debug:
       msg: Hello world